### ISSUE TITLE
Dockerized

### ISSUE THREAD

**Issue by Mega349** [butilka123/steamgifts-bot#11]
Hi butilka123,

i forked your bot to an [Dockerized version](https://gitlab.com/docker_repos/steamgifts-bot-dockerized) for private use , with some small changes like cookie check, priority pages and configurable (random) wait amount.
You can take a look if you want.

Your bot is running very well, i really like it ^^.

have a nice day

**Comment by butilka123** [comment]
Hi there, thanks a lot :)

Your idea is also very cool. Thanks for the Attributions. Have a nice day as well.
